### ISSUE TITLE
Installation gets stuck

### ISSUE THREAD

**Issue by dcrystalj** [Saeris/vue-spinners#2]
Hi. I have run `yarn add @saeris/vue-spinners` on my osx, but then installation gets stuck.
```
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > @saeris/vue-spinners@1.0.7" has unmet peer dependency "emotion@9.2.6".
warning " > @saeris/vue-spinners@1.0.7" has unmet peer dependency "vue-emotion@0.4.2".
[4/4] 📃  Building fresh packages...
[1/1] ⠂ @saeris/vue-spinners .  <- stuck here
```

**Comment by dcrystalj** [comment]
managed to resolve issue by closing VScode.

**Comment by Saeris** [comment]
Just published a fix for this. The problem is due to a postinstall script in `package.json` that was handling installing the example app's dependencies, which causes an infinite loop in yarn by building fresh packages. The example app requires the package from NPM rather than via a relative import to `src`, in order for it to work inside CodeSandbox. This should no longer be the case, as you'll have to manually install the example app if you want to run it locally.

Let me know if you still have problems with 1.0.8. I can only confirm that it's working in my local Windows environment and in Travis/Netlify.
